name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "step-1: hello world"
        run: echo "Hello World!!"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "step-1: goodbye world"
        run: echo "Goodbye World"
        shell: bash
